### ISSUE TITLE
The guide install waveshare 3.5 didn't work for me

### ISSUE THREAD

**Issue by Hyp3r10n** [Re4son/Re4son-Pi-TFT-Setup#1]
I follow exactly in your website but my lcd just show white screen. Can you give me an images kali with waveshare 3.5 tft inside ? Please help. My email: thehyp3r10n@gmail.com
Thank you !

**Comment by Re4son** [comment]
Hi Hyp3r10n,

Sorry to hear that the guide didn’t work for you. Unfortunately I don’t have an image for the Waveshare at the moment. I have ordered the screen you’ve got and it should arrive any day now.

Once I got it I will post an image straight away.

For now I can try to help you with a remote diagnosis. Could you please send me your /boot/config.txt?

Many thanks,

Re4son

**Comment by Hyp3r10n** [comment]
My /boot/config.txt/ is: 
`dtparam=spi=on
dtoverlay=waveshare35a`

**Comment by Re4son** [comment]
Hi Hyp3r10n,

my screen arrived and I’ve found the culprit: the SDL_MOUSEDEV is “/dev/input/event2” whereas it is “/dev/input/touchscreen” on the Adafruit ones.
I have created a waveshare branch of the pitftmenu.

Just do the following:

cd /home/pi/pitftmenu

git pull

git checkout waveshare

reboot

That should do the trick. The “screen off” function doesn’t work – I’ll look into that over the weekend.
Please let me know how you go.

Have fun,
Re4son

**Comment by Re4son** [comment]
SDL_MOUSEDEV should be “/dev/input/event2” for waveshare screens.
I've created a waveshare branch with this setting and tested successfully with a waveshare 3.5" display.
To activate, do:

```
cd /home/pi/pitftmenu
git pull
git checkout waveshare
reboot
```

**Comment by Hyp3r10n** [comment]
Can you give me the images kali fixed the lcd problem ?

**Comment by Re4son** [comment]
Hi Hyp3r10n,

there’s a bug in the setup of the waveshare screens for touch in terminal mode.
I’ve never noticed it because I usually took one of my existing adafruit images and just ran the waveshare setup over the top.
I’ll fix the bug over the weekend but for now you can get it to work by running:

cd /usr/local/src/re4son_kali-pi-tft_kernel*

sudo mount /dev/mmcblk0p1 /boot

sudo ./re4son-pi-tft-setup -t 35r -u /root

sudo ./re4son-pi-tft-setup -t wave35 -u /root

sudo nano /boot/config.txt

remove all sections from /boot/config.txt except one waveshare section.

I am currently uploading the image in case this won’t work for you.
I’ll let you know when the upload has finished.

Good luck,
Re4son

**Comment by Hyp3r10n** [comment]
OMG Worked ! thanks you very much but i want to ask how can i update my kali ? which package need to hold ?
